server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost:5432/truckplast_db
    username: postgres
    sql:
      init:
        mode: always
  mail:
    host: smtp.yandex.ru
    port: 587
    username: mm@opox.ru
    password: ioq9plmQ
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.yandex.ru
javax:
  mail:
    user: "mm@opox.ru"
    password: "ioq9plmQ"
    host: "imap.yandex.ru"
    folder: "SALE_HELPER"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method

file:
  path: "/truckplast-analyzer/file-store/"